export const LOGIN_STEP = 'LOGIN_STEP';
export const IS_LOGIN_COMPLETE = 'IS_LOGIN_COMPLETE';
export const IS_USER_NAME_AVAILABLE = 'IS_USER_NAME_AVAILABLE';
export const USER_NAME_RECOMMEND = 'USER_NAME_RECOMMEND';
export const SET_USR_NAME = 'SET_USR_NAME';
